delete 14x (15.08.2018-01.07.2016)
Über 12 Monate, Log vom 23.09.2019

1
15.08.2018 09:01
helmstedt, http://freifunk-elm-lappwald.de/api/helmstedt.json
Freifunk Helmstedt, Helmstedt
<class 'urllib.error.HTTPError'> HTTP Error 404: Not Found
WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.

2
15.08.2018 09:01
koenigslutter, http://freifunk-elm-lappwald.de/api/koenigslutter.json
Freifunk Königslutter, Königslutter
<class 'urllib.error.HTTPError'> HTTP Error 404: Not Found
WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.

3
15.08.2018 09:01
schoeppenstedt, http://freifunk-schoeppenstedt.de/api/schoeppenstedt.json
Freifunk Schöppenstedt, Schöppenstedt
<class 'urllib.error.HTTPError'> HTTP Error 404: Not Found
WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.

4
11.07.2018 06:01
wuppertal, http://api.freifunk-wuppertal.net/ffnet/ffwtal.json
Freifunk Wuppertal, Wuppertal
<class 'urllib.error.HTTPError'> HTTP Error 404: Not Found
WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.

5
04.05.2018 06:01
meissen, http://meissen.stadtlog.com/freifunk/FreifunkMeissen-api.json
Freifunk Meißen, Meißen
<class 'urllib.error.HTTPError'> HTTP Error 404: Not Found
WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.

6
20.04.2018 00:01
helgoland, https://meta.helgoland.freifunk.net/Helgoland-api.json
Helgoland, Helgoland
<class 'urllib.error.URLError'> <urlopen error timed out>
SocketException: Ein Socketvorgang bezog sich auf ein nicht verfügbares Netzwerk [2a01:4f8:d13:4f45::2]:443

7
11.07.2017 05:01
minden, http://www.freifunk-minden.de/api.json
Freifunk Minden, Minden
<class 'urllib.error.HTTPError'> HTTP Error 402: Payment Required
WebException: Der Remoteserver hat einen Fehler zurückgegeben: (402) Zahlung erforderlich.

8
23.06.2017 23:01
neuwied, https://freifunk-westerwald.de/api_neuwied.json
Neuwied, Neuwied
<class 'ssl.CertificateError'> hostname 'freifunk-westerwald.de' doesn't match either of '*.sedoparking.com', 'sedoparking.com'
AuthenticationException: Der HttpWebRequest.Host 'freifunk-westerwald.de' entspricht nicht dem X509Certificate.Subject 'sedoparking.com'.

9
08.04.2017 04:01
suhl, http://freifunk-suhl.de/FreifunkSuhl-api.json
Freifunk Suhl, Suhl
<class 'urllib.error.HTTPError'> HTTP Error 404: Not Found
WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.

10
21.12.2016 22:01
pulheim, http://api.freifunk-rhein-erft.de/FreifunkRhein-Erft-api.json
Freifunk Rhein-Erft, Pulheim
<class 'urllib.error.HTTPError'> HTTP Error 404: Not Found
WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.

11
22.09.2016 22:01
bergischgladbach, http://api.gl.wupper.freifunk-rheinland.net/bgl.json
Freifunk Bergisch Gladbach, Bergisch Gladbach
<class 'ssl.CertificateError'> hostname 'api.gl.wupper.freifunk-rheinland.net' doesn't match 'ffgl.eu'
WebException: Der Remotename konnte nicht aufgelöst werden: 'api.gl.wupper.freifunk-rheinland.net'

12
22.09.2016 22:01
burscheid, http://api.gl.wupper.freifunk-rheinland.net/bcd.json
Freifunk gl.wupper, Burscheid
<class 'ssl.CertificateError'> hostname 'api.gl.wupper.freifunk-rheinland.net' doesn't match 'ffgl.eu'
WebException: Der Remotename konnte nicht aufgelöst werden: 'api.gl.wupper.freifunk-rheinland.net'

13
22.09.2016 22:01
odenthal, http://api.gl.wupper.freifunk-rheinland.net/ode.json
Freifunk gl.wupper, Odenthal
<class 'ssl.CertificateError'> hostname 'api.gl.wupper.freifunk-rheinland.net' doesn't match 'ffgl.eu'
WebException: Der Remotename konnte nicht aufgelöst werden: 'api.gl.wupper.freifunk-rheinland.net'

14
01.07.2016 20:01
wahlsdorf, http://wahlsdorf.freifunk.net/wahlsdorf.json
Wahlsdorf, Wahlsdorf
<class 'urllib.error.HTTPError'> HTTP Error 503: Service Temporarily Unavailable
WebException: Der Remoteserver hat einen Fehler zurückgegeben: (503) Server nicht verfügbar.